### PR TITLE
Add ssl certs

### PR DESCRIPTION
**Pull request by mihai-cindea**
Hello @anojht 

I recently tried to use this image in Unraid, but unfortunately it seems it doesn't work without SSL, it seems it forces everything over https.
While I know this PR needs some work, I just want to know if you would be OK with merging the SSL scripts only, without the Unraid xml file, of course. The repository doesn't have Issues, so that's why I thought the only way would be to create a PR.
If you agree, then I can create another PR with cleaning the code a bit.

Cheers!

### CODE REVIEW

**Comment by anojht** [comment]
Hi no problem, I appreciate your contribution. I force https by default since its a payment system and needs to be secure. I thought people will already have letsencrypt setup somewhere and they can proxy this container. This is how I have my instance setup anyways.

I will merge as is with the template, thanks for your contribution!

**Comment by mihai-cindea** [comment]
Awesome! I didn't have time yet, I think I will somewhere next week.
Just to confirm, because I also don't want to break the current workflow: I see you have 443 open for plain traffic, do you use it to forward traffic from your LB or some Letsencrypt container? Thinking to make the SSL optional, and only enable it on Unraid by default.

**Comment by anojht** [comment]
I have Letsencrypt sitting in front of the container handling the ssl certificate for my domain. It just proxies traffic to the invoiceninja container. If we could make the ssl generation happen via a flag, let's say docker variable then that would work well. E.g `GEN_SSL = true | false`

**Comment by anojht** [comment]
Thanks for the PR. I am merging!

**Comment by mihai-cindea** [comment]
Oh, I also wanted to remove the Unraid file, I guess it can always be removed later :) 
Thank you, let me know if there are any issues! Cheers!

**Pull request merged**
